<a href="https://colab.research.google.com/github/pr3mek/data-sience-bootcamp/blob/main/template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.23.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1d Array

In [6]:
x = np.array([1, 3])
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [13]:
x.dtype

dtype('int32')

In [15]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [16]:
x.dtype

dtype('float64')

2d array

In [17]:
x = np.array([[1,2], [-3,4]])
print(x)

[[ 1  2]
 [-3  4]]


In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [20]:
x.dtype

dtype('int32')

In [21]:
x = np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [22]:
x.shape

(2, 3)